addpath ('Code');
addpath ('Auxiliary');
addpath ('SVM');
addpath ('Data');
addpath ('XuanyiFunction');
addpath ('XuanyiFunction/util');
addpath ('XuanyiFunction/experiments');
addpath ('visualization');
%addpath ('SVM/liblinear/matlab');
addpath ('SVM/libsvm/matlab');
%addpath ('Joint_Bayesian_Data');
%addpath ('Joint_Bayesian');
%addpath ('caffe/matlab');
%addpath ('MKL/liblinear-mkl/src/matlab');
%addpath(genpath('MKL/'));
%addpath(genpath('MKL/SVM-KM'));
%addpath(genpath('MKL/simplemkl'));
%addpath(genpath('MKL/SVM-KMExample'));
%addpath ('/home/dongxuanyi/mosek/7/toolbox/r2013a');
%addpath ('/home/dongxuanyi/mosek');
