# -------------------------------
# History settings
# -------------------------------
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoredups:erasedups
shopt -s histappend
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# -------------------------------
# Enable tab autocompletion
# -------------------------------
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
elif [ -f /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
fi

# -------------------------------
# LS Color support and aliases
# -------------------------------
export CLICOLOR=1
export LS_OPTIONS='--color=auto'
eval "$(dircolors -b)"
alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ..='cd ..'
alias ...='cd ../..'

# Git branch function (no echo!)
parse_git_branch() {
  git rev-parse --abbrev-ref HEAD 2>/dev/null
}

# Python venv name (no echo!)
venv_prompt() {
  [[ -n "$VIRTUAL_ENV" ]] && basename "$VIRTUAL_ENV"
}

# Set PS1 (no unintended line breaks or command output)
PS1='\[\e[36m\]\u@\h\[\e[0m\] \[\e[33m\]\w\[\e[0m\] \[\e[32m\]$(venv_prompt)$(parse_git_branch)\[\e[0m\] \$ '


# -------------------------------
# Misc Bash options
# -------------------------------
shopt -s checkwinsize       # Resize-aware
shopt -s globstar           # Recursive ** globbing
shopt -s cmdhist            # Multi-line commands in one history entry
shopt -s extglob            # Extended globbing
